### ISSUE TITLE
Add `desription` to `skills.create` function

### ISSUE THREAD

**Issue by martyna-mindsdb** [mindsdb/mindsdb_python_sdk#109]
**Is your feature request related to a problem? Please describe.**
Currently, the `skills.create` method does not allow users to add description to a skill, which is relevant for an agent to choose which skill to use.

**Describe the solution you'd like**
Please add the `description` argument o this function.

**Comment by kom-senapati** [comment]
I want to work on this

**Comment by martyna-mindsdb** [comment]
This has been already resolved.
