### ISSUE TITLE
Test pandas accessor with cloud

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_python_sdk#11]
Make sure all the pandas accessor tests (same as the ones currently done for native, same as the ones that will be done in #10) also work when connecting to mindsdb cloud (use a testing account, add the credentials to .mindsdb_credentials.json)

**Comment by ilia-tsyplenkov** [comment]
Implemented in https://github.com/mindsdb/mindsdb_python_sdk/pull/18 and https://github.com/mindsdb/mindsdb_python_sdk/pull/17
