### ISSUE TITLE
Resolve issues with Authorizers

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_python_sdk#23]
There is a `BaseAuthorizer` currently, this is never used.
There is a `CloudAuthorizer`, this doesn't work properly, it should:
a) Login and get a token
b) Keep setting that token as a cookie

Please add a 3rd authroizer (or 2nd, since I think the `BaseAuthorizer` can be removed) called `UrlTokenAuthorizer` which get activated when a `url_token` parameter is passed to the SDK's `__init__` and sets the url parameter `apikey={url_token}` for all requests.

In order to test the `CloudAuthorizer` enable cloud tests with `clouda.mindsdb.com`, not the best solution but  a good enough temporary workaround (I'll add an invite code in the `$CLOUD_INVITE_CODE` secret, which can be used for creating the users)

**Comment by ilia-tsyplenkov** [comment]
Done. There is one fail reason, but it is on cloud side.
