### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by arsen3d** [mindsdb/mindsdb_python_sdk#28]
Example fails because predictor tries to predict before the data is learned.
Also, current documentation shows how to get the predictor from mdb.predictors.learn the method.
I would expect that normally predict will rarely be called in such a context. 
Proposal to load predictor using load method would be preferred as suggested in https://github.com/mindsdb/mindsdb_python_sdk/issues/27

```
from mindsdb_sdk import SDK

# connect
mdb = SDK('http://localhost:47334')

# upload datasource
mdb.datasources['home_rentals_data'] = {'file' : 'home_rentals.csv'}

# create a new predictor and learn to predict
predictor = mdb.predictors.learn(
    name='home_rentals',
    datasource='home_rentals_data',
    to_predict='rental_price'
)

# predict
result = predictor.predict({'initial_price': '2000','number_of_bathrooms': '1', 'sqft': '700'})
```

**Comment by ilia-tsyplenkov** [comment]
@arsen3d Thanks for the issue. You are right.
Before making prediction need to make sure that training process is finished.
Here is a way how to do it:
```
# create a new predictor and learn to predict
predictor = mdb.predictors.learn(
    name='home_rentals',
    datasource='home_rentals_data',
    to_predict='rental_price'
)
# waiting when learning will finished
while predictor.get_info()['status'] != 'complete':
    print("training process is still in progress")
    time.sleep(10)

# predict
result = predictor.predict({'initial_price': '2000','number_of_bathrooms': '1', 'sqft': '700'})

**Comment by ilia-tsyplenkov** [comment]
I'll fix this example today

**Comment by ilia-tsyplenkov** [comment]
Fixed in staging.

**Comment by arsen3d** [comment]
This is an improvement, but I still think there is a need to show example of how to “load” the predictor without having to call “learn” method. 

In real world projects “learn” will be done in a context different from “predict”.  

I did this by calling the “__getitem__” method, which is not very pretty. Lets make the python sdk mirror javascript sdk, which used “Load” method prior to calling “predict”
