### ISSUE TITLE
Not work with MindsDB 23.2.3.1

### ISSUE THREAD

**Issue by YishuiLi** [mindsdb/mindsdb_python_sdk#41]
**Your Environment**

* Python version: Python3.8.16
* Operating system: CentOS7
* Mindsdb Python SDK version: 0.16.1

**Please describe your issue and how we can replicate it**
Python SDK not work with MindsDB 23.2.3.1

**Comment by ZoranPandovski** [comment]
Hi @YishuiLi, the current version is outdated. For now, only the js_sdk is fully functional. We are going to release a new version with the python_sdk in  the next few weeks

**Comment by YishuiLi** [comment]
Got it. Thanks!
