### ISSUE TITLE
Use DALL-E with the SDK 

### ISSUE THREAD

**Issue by smyja** [mindsdb/mindsdb_python_sdk#58]
I'd like to use Dall-E with the SDK.

**Comment by ea-rus** [comment]
Using this [tutorial](https://mindsdb.com/blog/tutorial-how-to-add-ai-image-generation-to-your-own-app) you can create model and use it from python sdk. In respond of '.predict' method you will get url to image and you need to download it using requests.

**Comment by smyja** [comment]
> Using this [tutorial](https://mindsdb.com/blog/tutorial-how-to-add-ai-image-generation-to-your-own-app) you can create model and use it from python sdk. In respond of '.predict' method you will get url to image and you need to download it using requests.

Thanks,I'll check it out.
