### ISSUE TITLE
Error on running make on windows

### ISSUE THREAD

**Issue by SebastianJames55** [mindsdb/mindsdb_python_sdk#64]
**Staging**

* Python version: 3.9
* Operating system: Windows 10
* Mindsdb Python SDK version: 1.0.5

**Please describe your issue and how we can replicate it**
As per [mindsdb python sdk docs](https://github.com/mindsdb/mindsdb_python_sdk/issues/docs.mindsdb.com/sdk/python-sdk#advanced-installation) running .\make html gives
```
Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
```

**Comment by SebastianJames55** [comment]
@ZoranPandovski I came across this issue while setup, can I please be assigned to this issue?

**Comment by ZoranPandovski** [comment]
You need to install dependencies before running it. Did you install the requirements?

**Comment by SebastianJames55** [comment]
I missed that basic step which was already mentioned in the [docs](docs.mindsdb.com/sdk/python-sdk#advanced-installation) & ended up doing ```pip install sphinx_rtd_theme``` manually. When I got the sdk working I got too excited & acted too soon. 
I should have at least cross-checked whether the fix I had in mind was already there. I'm terribly sorry. I'll close this issue. 

Next time, I'll take extra care of the doc & ask in the community/discussion before raising an issue.

**Comment by SebastianJames55** [comment]
I must, however, note that in the documentation there's a step mentioning ```pip install sphinx```. But this is already there in the requirements. This might have put me off by a little when I was rushing through. Can I can raise this as another issue to improve the docs?
