### ISSUE TITLE
Drop project with '-' in name

### ISSUE THREAD

**Issue by ea-rus** [mindsdb/mindsdb_python_sdk#65]
Steps to reproduce:

```python
c=mindsdb_sdk.connect()

p=c.create_project('mind-reader-project')

c.drop_project('mind-reader-project')
```
Raises:
```
SQL statement cannot be parsed by mindsdb_sql - DROP DATABASE mind-reader-project: Syntax error at token MINUS: "-"
```

**Comment by SebastianJames55** [comment]
@ea-rus hi 👋🏼  
Just to clarify, the fix is allowing to drop project with '-' in name. 
My understanding was creation of project with '-' in name shouldn't allowed in the first place (similar to @Mr-Destructive fix for #67). The same isn't allowed in mindsdb cloud using sql.

**Comment by ea-rus** [comment]
Yes, it is allowing to use '-' in name. The reasons:
- if user already has project with '-' it should be possible to remove it
- mindsdb web editor allows to use '-': 
```create project `asdf-adf` ```

**Comment by SebastianJames55** [comment]
I just checked in mindsdb cloud editor
`create project mind-reader-project;` gave 
`SQL statement cannot be parsed by mindsdb_sql - create project mind-reader-project: Syntax error at token MINUS: "-"
`

**Comment by SebastianJames55** [comment]
Oh ok, understood. Thank you for pointing that out.
