### ISSUE TITLE
'Upload BYOM files' method from python SDK

### ISSUE THREAD

**Issue by tomhuds** [mindsdb/mindsdb_python_sdk#76]
e.g.

`def upload_byom(model_name: str, model_file: str, requirements_file: str)
`
Will require an update to our byom upload endpoint

**Comment by ea-rus** [comment]
byom upload creates the new ml engine

Maybe is better to:
```python
byom_engine = con.ml_engines.create_byom(model_code: str, requirements_code: str)
```
or
```python
byom_engine = con.ml_engines.create_byom(path_to_model_code: str, path_to_model_requirements: str)
```

Also we can try to implement option to extract code and requirements from module
```python
byom_engine = con.ml_engines.create_byom(<imported python module or class>)
```
