### ISSUE TITLE
Cannot Create Models for Projects with Mixed Case Names (e.g. MyProject)

### ISSUE THREAD

**Issue by radiantone** [mindsdb/mindsdb_python_sdk#79]
**Your Environment**

* Python version: 3.10.x
* Operating system: Ubuntu 22.04
* Mindsdb Python SDK version:
* mindsdb-sdk==1.0.4
mindsdb-sql==0.6.7

* Additional info if applicable:

**Please describe your issue and how we can replicate it**
Once you create a project with mixed case e.g. "MyProject", you cannot create models as it throws exception "Project doesn't exist "myproject"

**Comment by ea-rus** [comment]
Tested project in mixed case, it works now.
