### ISSUE TITLE
When the project name is the same as the database name nothing works

### ISSUE THREAD

**Issue by radiantone** [mindsdb/mindsdb_python_sdk#81]
**Your Environment**

* Python version:
* Operating system:
* Mindsdb Python SDK version:
* Additional info if applicable:
When I have a project called 'housing' with a database called 'housing' it cannot create models, jobs etc.

**Please describe your issue and how we can replicate it**

**Comment by ea-rus** [comment]
I confirm this problem: we can create database with project name and vice versa. But it has to be controlled by mindsdb server.
