### ISSUE TITLE
The SDK Docs indicate model.predict() can accept a dict, but it doesn't

### ISSUE THREAD

**Issue by radiantone** [mindsdb/mindsdb_python_sdk#84]
**Your Environment**

* Python version:
* Operating system:
* Mindsdb Python SDK version:
* Additional info if applicable:

**Please describe your issue and how we can replicate it**
Code is inconsistent with the docs
https://mindsdb.github.io/mindsdb_python_sdk/model.html?highlight=predict

**Comment by radiantone** [comment]
def predict(self, data: Union[pd.DataFrame, Query], params: dict = None) -> pd.DataFrame:
        """
        Make prediction using model

        if data is dataframe it uses /model/predict http method and sends dataframe over it
        if data is select query with one table it replaces table to jon table and predictor
        and sends query over sql/query http method

        if data is select from join other complex query it modifies query to:
          'select from (input query) join model' and sends it over sql/query http method

        :param data: dataframe or Query object as input to predictor
        :param params: parameters for predictor, optional
        :return: dataframe with result of prediction
        """
        if isinstance(data, Query):

**Comment by ea-rus** [comment]
python annotation is not complete, but model.predict can accept a dict
I will fix it
