### ISSUE TITLE
Get mindsdb server version

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_python_sdk#85]
**Is your feature request related to a problem? Please describe.**
It should be possible to get the MindsDB server version through our SDKs.

**Describe the solution you'd like**
For example:

```python
import mindsdb_sdk
server = mindsdb_sdk.connect('http://127.0.0.1:47334')
server.version()  # should return a version string, e.g. '23.10.1.0' 
```

This will be useful for our benchmarking suite.

**Comment by ea-rus** [comment]
Would be this option ok?
```python
print(server.status()['mindsdb_version'])
```
It uses this '/api/status' method and works for local version
Cloud doesn't return version at the moment
https://cloud.mindsdb.com/api/status

**Comment by paxcema** [comment]
Oh, nice! Thanks, this is useful. Perhaps it should be documented?

**Comment by ea-rus** [comment]
Added to docs
https://mindsdb.github.io/mindsdb_python_sdk/server.html#mindsdb_sdk.server.Server.status
