### ISSUE TITLE
RuntimeError: Database is not defined

### ISSUE THREAD

**Issue by pranavvp16** [mindsdb/mindsdb_python_sdk#92]
Seems the latest release of mindsdb_sdk broke the `create_model` method. I checked this the create_model method works correctly in `2.0.0` while it fails in `2.1.0` with this error 
![image](https://github.com/mindsdb/mindsdb_python_sdk/assets/94780581/b92bf7e4-37ae-4588-bce0-1b8ac7315d40)
I saw the code lines, if database parameter is optional then why raise runtime error at line 467 with `if database is None`

**Comment by pranavvp16** [comment]
<img width="767" alt="Screenshot 2024-01-18 at 9 40 00 PM" src="https://github.com/mindsdb/mindsdb_python_sdk/assets/94780581/d481c2b0-4b6f-44ee-ac92-a072555baf8b">

**Comment by ea-rus** [comment]
Thanks for inspecting the problem.
Fixed in version 2.1.1. Please check it
